# Generated by Django 6.0.6 on 2026-06-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0003_tag_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
