# Generated by Django 6.0.6 on 2026-06-26 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0004_tag_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['order']},
        ),
    ]
