# Generated by Django 6.0.7 on 2026-08-02 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0008_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
    ]
